[tool.briefcase]
project_name = "Android_Dev_Board"
bundle = "com.mark"
version = "0.0.1"
url = "https://mark.com/android_dev_board"
license = "BSD license"
author = 'Mark Wu'
author_email = "markwu.ca@gmail.com"

[tool.briefcase.app.android_dev_board]
formal_name = "Android_Dev_Board"
description = "Testing Blinkah library with Beeware"
icon = "src/android_dev_board/resources/android_dev_board"
sources = ['src/android_dev_board']
requires = ['pyftdi>=0.51.2','pyusb>=1.0.2','Adafruit-Blinka>=5.3.0']


[tool.briefcase.app.android_dev_board.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.android_dev_board.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.android_dev_board.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
    'pyftdi>=0.51.2','pyusb>=1.0.2','Adafruit-Blinka>=5.3.0'
]

# Mobile deployments
[tool.briefcase.app.android_dev_board.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.android_dev_board.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
